### ISSUE TITLE
UX: `sky queue` gets stuck for a while when checking a stopped `sky-spot-controller`

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1042]
```
» sky queue                    2 ↵
Fetching and parsing job queue...
Cluster bench is not up (status: STOPPED); skipped.

Job queue of cluster sky-spot-controller
ssh: connect to host 44.199.255.174 port 22: Operation timed out

Failed to get job queue on cluster sky-spot-controller.

Cluster xv2test is not up (status: STOPPED); skipped.
Cluster c2 is not up (status: STOPPED); skipped.
Cluster xv2test2 is not up (status: STOPPED); skipped.
Local cluster on-prem-smoke-test is uninitialized; skipped.
```
After the line `Job queue of cluster sky-spot-controller` the output is stuck for tens of seconds. Perhaps in this case we should try to refresh its status? (here, the controller has a cached UP status, but is in fact stopped).

**Comment by mraheja** [comment]
This issue seems to still happen (except now it doesn't show ssh timed out, just stalls for a while), but after some exploration, I found that the slowdown is just because cluster status refreshing in `_update_cluster_status_no_lock` takes a very long time. I can look into this, but I'm guessing refreshing just takes a while anyways so not sure how useful that would be?

**Comment by concretevitamin** [comment]
> I'm guessing refreshing just takes a while anyways so not sure how useful that would be?

Agreed. It's indeed the refresh -> query IPs part taking a while. Closing for now.
