### ISSUE TITLE
Default scheduling demand `CPU:0.5` can be confusing 

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1045]
In `sky queue` - `[CPU:0.5]`  means this task takes 0.5 cpu for **scheduling purpose**.  So e.g., if the VM has 8 cores, this means we can concurrently run at most 16 tasks.

However, when the actual task is run, it is run with an env var `OMP_NUM_THREADS=1` which means if the code uses any openmp code, this task will get 1 core only.

So there's a confusing mismatch here. It seems better  to change the default demand to `CPU:1` so there's no mismatch.

Related to but different than #243 #951. Reported by Justin.

**Comment by romilbhardwaj** [comment]
I do not think we should set `CPU: 1` globally for all tasks.

Until we allow users to specify CPUs as a resource requirement, I would advocate for keeping it at 0.5, or maybe even reducing it to 0.25 or 0.1.  Many workloads _rarely_ hit 100% CPU utilization because they are blocked on disk, network or hw accelerators. We want to allow multiple sky tasks to be scheduled together and let the kernel CFS handle CPU time sharing. The exact number we choose (1, 0.5, 0.25) is really just placing a bet on the average CPU utilization of the typical sky task, and I would put my money on < 0.5. 

afaik, `OMP_NUM_THREADS=1` is simply setting the number of _software_ threads that are created by openmp. This number can be much larger than the number of hardware threads on the node and can be easily overriden by the user if required (e.g. #243). Since this is not a hard constraint, I don't think this should be a compelling reason to use `cpu:1` when submitting the sky ray task. 

Side rant: This problem seems to be stemming from Ray's (lack of) CPU scheduling, which simply uses the `cpu` demand for bookkeeping - it does not set the CPU affinity for the worker process for the kernel to know which CPU to bind the process to. This effectively results in a free-for-all contest for CPU among ray tasks, which is eventually mediated by the kernel scheduling policy. `cpu` in Ray is really a misnomer, it actually only reflects the number of concurrent tasks that can run.

**Comment by Michaelvll** [comment]
This is raised by another user
> It seems that the resource usage output (CPU:0.5) of sky queue is a bit confusing when jobs are launched by spot controller.

> either sky queue just lists the spot controllers that are running but not the individual spot jobs (but suggesting the user to use sky spot queue to list individual spot jobs), or they can be listed and resource should match the output of sky spot queue
As a user I probably prefer the latter.
