### ISSUE TITLE
sky start may unexpectedly launch a new VM

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1054]
Mentioned by @Michaelvll in https://github.com/skypilot-org/skypilot/pull/1014#discussion_r940537044, below scenario may trigger an unexpected behavior of `sky start`.

1. User `sky launch gpunode` and got a VM in `us-west-1a`
2. User `sky stop` it
3. After a while, user `sky start` again. but there's no capacity in `us-west1-a`. Now ray up would try to start a new cluster in `us-west-1b` because in Ray YAML all possible zones under `us-west-1` will be considered.

To resolve this we should disable failover behavior for `sky start`. We may need to patch Ray autoscaler to fix this bug.

**Comment by concretevitamin** [comment]
See https://github.com/skypilot-org/skypilot/issues/640 for a possible solution?

**Comment by Michaelvll** [comment]
> See #640 for a possible solution?

The solution may not be sufficient, as we cannot change the `availability_zones` field to the zone where the old cluster was on (otherwise, ray will consider the yaml different with the previous one, and launch a new cluster), so ray up can still launch the cluster on another zone if the previous one does not have enough resources.

**Comment by infwinston** [comment]
@Michaelvll Just to clarify the behavior of Ray, when we `ray up` a stopped VM in `us-east-1b` with 
```
availability_zone: us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e,us-east-1f
```
and fail due to no resources. What would Ray do? Throw an error or try to launch another VM in other zones automatically?
(i.e., does Ray support failover to other zones)

**Comment by Michaelvll** [comment]
> @Michaelvll Just to clarify the behavior of Ray, when we `ray up` a stopped VM in `us-east-1b` with
> 
> ```
> availability_zone: us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e,us-east-1f
> ```
> 
> and fail due to no resources. What would Ray do? Throw an error or try to launch another VM in other zones automatically? (i.e., does Ray do silent failover to other zones)
> 
> If `ray up` just throws error, then we can just disable any sort of failover on our end for `sky start` and the above issue won't occur right?

Ahh, good point! Actually, I cannot confirm what is the actual behavior. I believe it will try to launch it in another zone, if the original one does not work, since the purpose of ray autoscaler is to satisfy users' requirement for the number of nodes no matter it is a cached node or a new one. We may need to take a look at the source code to see the actual behavior

**Comment by Michaelvll** [comment]
One solution is to update the `ray-launch-hash` tag of the instance of the config that only has the `AvailabililtyZone` that the launched instance actually belongs to after the instance is launched.

**Comment by concretevitamin** [comment]
Bumping this up to P0. This has possibly happened in real scenarios.
