### ISSUE TITLE
Shared sky status

### ISSUE THREAD

**Issue by tonxxd** [skypilot-org/skypilot#1138]
Hi and thanks for this amazing project!

I need to fire the sky task from within a docker container. This means that right now, every time I run the docker container a `.sky` folder is created in the container fs. 
Obviously when i type `sky status` from my laptop i don't see any cluster. Even using the `-r` flag (to fetch the status from the cloud provider) it does not show any cluster. 

I tried to mount the `.sky` folder of my laptop to the container but i think there is a conflict of users and I get 
`FileNotFoundError: [Errno 2] No such file or directory: '/root/.sky/generated/workload.yml'`

Any idea or similar issue i could look at? Also It would be useful to store the state into a shared object store. 

Ps. I think the `-r` flag of the `sky status` command could regenerate the status from the existing vms on the cloud (based on tags / names the user can access) even if the cluster is not registered locally.

**Comment by tonxxd** [comment]
Thanks @concretevitamin 
It's not a blocker but i am trying to find a solution to avoid the issue. I'll look at the code to see if i manage to contribute, if you have ideas please let me know :)

**Comment by concretevitamin** [comment]
@tonxxd Got it. One potential workaround is when constructing `ResourceHandle`, pass in a relative path for the `cluster_yaml` field.  Namely rather than storing `/root/.sky/generated/sky-5204-root.yml`, we can store `~/.sky/generated/sky-5204-root.yml`. This way with some mounting & permission tricks the container should be able to share the host's status information.

Perhaps try doing the absolute -> relative conversion in the handle's constructor?:

https://github.com/skypilot-org/skypilot/blob/0c2b291b03abe486b521b40a3069195e56b62324/sky/backends/cloud_vm_ray_backend.py#L1449

**Comment by concretevitamin** [comment]
@tonxxd This has been fixed by @Michaelvll. Let us know if it works for you - here's a snippet for your docker use case:

https://github.com/skypilot-org/skypilot/pull/1176#pullrequestreview-1124627059

**Comment by tonxxd** [comment]
Great, thanks @concretevitamin ! I'll update the comment when I try
