### ISSUE TITLE
[Storage] Zombie entries in `sky storage ls` when deleted externally

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1313]
Currently storage objects can be deleted by the spot controller. This results in zombie entries in the `sky storage ls` on the user's laptop. We need way to refresh the local state or maybe show only persistent entries.

**Comment by romilbhardwaj** [comment]
Reported by user:

> Also, sky storage ls shows a ton of different buckets, but on the gcp console, there aren't that many buckets

**Comment by landscapepainter** [comment]
@romilbhardwaj I'm a bit confused on what's going on with this and #795. Trying to confirm if I'm getting it correct.

Here, it seems like storage created in the users laptop gets deleted by the spot controller when spot job uses the storage and ends the task successfully. Then, since `sky storage ls` cannot sync with externally removed storages, it shows zombie entires. Is this correct? If so, the solution to this is to sync `sky storage ls` with external deletion.

And for #795 , resource leakage can happen when storages created by the spot controller does not get removed after successful run of the spot job as the storage will be removed only after the task completes. And your suggestion to resolve this is to manage the storage created by the spot controller in the users laptop rather than the spot controller. Is this correct? If so, how is #795 and this issue a duplicate? Do they share a identical solution?

**Comment by romilbhardwaj** [comment]
Great observation @landscapepainter. Your understanding of both issues is correct. 

#795 is somewhat different from this issue. This issue deals with buckets deleted at the spot controller or externally. #795 has the inverse problem - buckets created on spot controller will not show up in local `sky storage ls`. 

However, #795 and this issue share a common solution - sync `sky storage ls` state with the actual buckets on the cloud provider. This sync will ensure any buckets created by the spot controller get added to the client's `sky storage ls` and deleted buckets get removed.

I'll reopen #795, but note there that it shares the solution with this issue.
