### ISSUE TITLE
[Feature Request] Export `SKY_NODE_IPS` and `SKY_NODE_RANK` outside of `run` 

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1336]
These two environment variables mentioned above are only accessible in the `run` function - when the Ray job is executed. This conflicts with distributed training, where these variables are needed in the setup step of the task. Hence, it is a good feature to have these environment variables earlier in stages of a Task.

**Comment by iojw** [comment]
@michaelzhiluo Do you have a specific example of how the `SKY_NODE_RANK` variable will be used in the setup step?

I believe that we can make the `SKY_NODE_IPS` and `SKY_NODE_RANK` variables available in the setup step by moving the logic implemented in #1291 to the setup step, but the issue with this is that the `SKY_NODE_RANK` variable for a particular node may differ in the setup and run step. 

This is because setup on all nodes in a cluster, but tasks may be run only a subset of the nodes in the cluster. Therefore, the rank of a node may differ between the setup and run step, which may lead to confusion.

**Comment by michaelzhiluo** [comment]
@iojw This git issue was raised in reponse to a user request to have `SKY_NODE_RANK` and `SKY_NODE_IPS` available to the machine when you SSH into it.

This is definitely a design question whether`SKY_NODE_RANK` should be tied to the cluster or the task. We should have an offline discussion about this, but I think we should have two separate environment variables for 1) cluster (`SKY_NODE_RANK`) and 2) task (`SKY_TASK_RANK`) to get the best of two worlds.

**Comment by concretevitamin** [comment]
> Hence, it is a good feature to have these environment variables earlier in stages of a Task.

 I do not think the user wanted the variables in setup, or other stages. He wanted the env vars when he SSH'd into the machine, like you mentioned:

> a user request to have SKY_NODE_RANK and SKY_NODE_IPS available to the machine when you SSH into it.

**Comment by michaelzhiluo** [comment]
```
I do not think the user wanted the variables in setup, or other stages. He wanted the env vars when he SSH'd into the machine, like you mentioned:
```

If the variables are in the SSH'd machine, it will naturally appear in `setup`. This is a very reasonable extension due to distributed training setup, when you want to automatically export environment variables for Tensorflow distributed training, for example.

```
 I think we should have two separate environment variables for 1) cluster (SKY_NODE_RANK) and 2) task (SKY_TASK_RANK) to get the best of two worlds.
```

I'm pushing this forward. It is clear that a lot of future users will experience the same issue. @concretevitamin

**Comment by romilbhardwaj** [comment]
Should be kept open - some more recent reports in #1720

**Comment by concretevitamin** [comment]
Being fixed in https://github.com/skypilot-org/skypilot/pull/2617
