### ISSUE TITLE
SkyPilot runtime setup fails on Ubuntu Server AMIs

### ISSUE THREAD

**Issue by WoosukKwon** [skypilot-org/skypilot#1616]
I failed to launch AWS VMs with the following Ubuntu Server AMIs (which are not deep learning AMIs).

* Ubuntu Server 22.04 LTS (HVM)
`sky launch -c ubuntu2204 --cloud aws --region us-east-1 --image-id ami-00874d747dde814fa`

* Ubuntu Server 20.04 LTS (HVM)
`sky launch -c ubuntu2004 --cloud aws --region us-east-1 --image-id ami-0778521d914d23bc1`

**Comment by WoosukKwon** [comment]
Thanks for taking this @infwinston !

**Comment by infwinston** [comment]
This issue is actually non-trivial.. After some investigation, if we `sky launch` this particular AMI, it'll be stuck forever during `ray up`. The reason is the `sudo` command is hanging and asking for password which is not supposed to happen.
Interestingly, if I launch an instance with AWS console then everything works normally.

Diving deeper (also had a discussion with Simon), this seems to be related to the usage of `UserData`
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html
https://github.com/skypilot-org/skypilot/blob/8d6f6a9ce1d7530c7adc48e80b4154b63220c180/sky/authentication.py#L97-L104
If I remove this `UserData` field, the VM seems to be set up correctly and `sudo` works.

My hypothesis is somehow when `UserData` is specified, the default cloud-init script is not triggered correctly. hence `ubuntu` is not added to the sudoer list. 

I think this is a serious bug given that this AMI is the default ubuntu image.

@concretevitamin @Michaelvll is there any reason we use `UserData` to add keys to `~/.ssh/authorized_keys` rather than just using the `KeyName` field?

**Comment by infwinston** [comment]
Ah I think it's related to this PR, in which we replace `KeyName` with `UserData`.
https://github.com/skypilot-org/skypilot/pull/1427

**Comment by infwinston** [comment]
From https://cloudinit.readthedocs.io/en/latest/reference/examples.html#including-users-and-groups, by adding 
```
shell: /bin/bash
sudo: ALL=(ALL) NOPASSWD:ALL
```
to
```
    for node_type in config['available_node_types']:
        config['available_node_types'][node_type]['node_config']['UserData'] = (
            textwrap.dedent(f"""\
            #cloud-config
            users:
            - name: {config['auth']['ssh_user']}
              shell: /bin/bash
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh-authorized-keys:
                - {public_key}
            """))
    return config
```
The following command works normally now
```
sky launch -c ubuntu2004 --cloud aws --region us-east-1 --image-id ami-0778521d914d23bc1
```
