### ISSUE TITLE
[TPU] ray_up retry can cause preemption leak for spot TPUs

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1716]
In `cloud_vm_ray_backend.py`, we may re-run `ray up` several times if we think ssh connection wasn't successful.
However, another `ray up` can cause TPUs preemption leakage as the ray up failure was indeed caused by preemption.

Logs below:

```
I 02-23 07:12:59 cloud_vm_ray_backend.py:1450] Launching on GCP us-central1 (us-central1-f)
D 02-23 07:12:59 cloud_vm_ray_backend.py:142] `ray up` script: /tmp/skypilot_ray_up_ah76pcbc.py
I 02-23 07:17:18 log_utils.py:45] Head node is up.
I 02-23 07:19:41 cloud_vm_ray_backend.py:1500] Retrying runtime setup due to ssh connection issue.
I 02-23 07:19:41 cloud_vm_ray_backend.py:1521] Retrying launching in 6.7 seconds.
D 02-23 07:19:48 cloud_vm_ray_backend.py:142] `ray up` script: /tmp/skypilot_ray_up_ozwkju4c.py
I 02-23 07:23:18 log_utils.py:45] Head node is up.
D 02-23 07:24:44 cloud_vm_ray_backend.py:1528] `ray up` takes 705.1 seconds with 2 retries.
I 02-23 07:24:45 cloud_vm_ray_backend.py:1263] Successfully provisioned or found existing VM.
W 02-23 07:24:46 backend_utils.py:1381] Found more than one TPU VM/Pod with the same cluster name sky-ce66-gcpuser-161 in zone us-central1-f.

D 02-23 07:24:47 backend_utils.py:1404] TPU VM ray-sky-ce66-gcpuser-161-head-bbb44751-tpu is in PREEMPTED state. Skipping IP query... Hint: make sure it is not leaked.
W 02-23 07:24:49 backend_utils.py:1381] Found more than one TPU VM/Pod with the same cluster name sky-ce66-gcpuser-161 in zone us-central1-f.

D 02-23 07:24:50 backend_utils.py:1404] TPU VM ray-sky-ce66-gcpuser-161-head-bbb44751-tpu is in PREEMPTED state. Skipping IP query... Hint: make sure it is not leaked.
```

https://github.com/skypilot-org/skypilot/blob/c94b43bb2a34538b5e88ad26081d1b498765ea0f/sky/backends/cloud_vm_ray_backend.py#L1519-L1524

Looks like this retry is originally for Azure from this PR https://github.com/skypilot-org/skypilot/pull/985.
I'm not sure if this retry will also cause some leakage for CPU/GPU spot instances. 
Is it possible to distinguish between preemption or ssh failure? or is it safer to just exclude spot instance from this retry logic?
cc @Michaelvll @concretevitamin

**Comment by concretevitamin** [comment]
This makes sense, and maybe one fix is to simply remove this block? It sacrifices some convenience and seems to help with the situation here.

https://github.com/skypilot-org/skypilot/blob/c94b43bb2a34538b5e88ad26081d1b498765ea0f/sky/backends/cloud_vm_ray_backend.py#L1519-L1524

> I'm not sure if this retry will also cause some leakage for CPU/GPU spot instances.

Is the problem at hand that a TPU in a "preempted" state does not get cleaned up by the cloud provider. In contrast, preempted CPU/GPU instances on GCP/AWS/... do seem to get cleaned up?

I think we're pretty confident on AWS, such "leakage" does not happen due to prolonged usage.

IIRC, on GCP previously, preempted CPU instances sometime do stay in "stopped" state.

**Comment by infwinston** [comment]
For AWS and GCP, I think the termination behavior depends on the launch config, https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/interruption-behavior.html
https://cloud.google.com/compute/docs/instances/create-use-spot#identify

For example in GCP, by default `instanceTerminationAction` is set to `STOP` so a preempted VM will be turned into "stopped" state.
```
where TERMINATION_ACTION indicates which action to take when Compute Engine preempts the VM, 
either stop (STOP) or delete (DELETE) the VM. If the instanceTerminationAction field is missing, 
the default value is STOP.
```

IIRC our spot controller will first try to relaunch the same resource+disk. if it fails, it'll teardown the cluster. in this case, if the second `ray up` can reuse the first preempted resource then it should be fine. if not we might also have leakage there. is this correct? @Michaelvll

**Comment by Michaelvll** [comment]
For the retrying logic here, it is quite stale. We should directly change our `node_provider` like the following to adopt the retry instead of rerunning the `ray up` outside. 
https://github.com/skypilot-org/skypilot/blob/b1aadf676cbe61ff9a19672ff694b142e354ac3b/sky/skylet/providers/gcp/node_provider.py#L306-L328

 > IIRC our spot controller will first try to relaunch the preempted/stopped resource+disk. if it fails, it'll teardown the cluster. in this case, if the second ray up can reuse the first preempted/stopped resource then it should be fine. if not we might also have leakage there. is this correct?

For GCP, our failover is zone based, if the cluster is preempted and stopped, the retrying for the `ray up` will just try to start the same VM in the same zone, which works for non-TPU VMs. If it fails to start, the failover logic will call `teardown_no_lock` to cleanup the VM in the current zone.

For AWS, the default preemption behavior is termination ([ref](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/interruption-behavior.html#specifying-spot-interruption-behavior)), so no leakage will happen in this case.
