### ISSUE TITLE
“sky down --purge” does not work after I switch GCP users

### ISSUE THREAD

**Issue by merrymercy** [skypilot-org/skypilot#1761]
## How to reproduce 

1. Login with user A and manually shut down a cluster
```
gcloud init
gcloud auth application-default login
sky launch -c mycluster hello_sky.yaml
ssh mycluster
  - sudo shutdown -h now
```

2. Login with user B and try to delete `mycluster`
```
gcloud init
gcloud auth application-default login
sky down -p mycluster  # This does not work
```

<img width="986" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/15100009/224438985-1b9ea4b7-908f-40f9-8f21-1fff632a8019.png">

**Comment by infwinston** [comment]
Thanks for filing the issue! (related issue https://github.com/skypilot-org/skypilot/issues/1756)
At this moment SkyPilot assumes users use one GCP config at a time so this is expected behavior.
(correct me if I'm wrong @Michaelvll )

Could you try if switching account/project by the following commands and see if `sky down` works?
```
gcloud config configurations list
gcloud config configurations activate <CONFIG_NAME>
```

**Comment by merrymercy** [comment]
I see. My assumption is that `--purge` should ignore all errors and forcibly delete all things.
Is this the intended behavior?  Either way, this is a minor bug.

**Comment by infwinston** [comment]
This is a good point! Should `--purge` ignore all errors including identity mismatched if user really want to remove the row?
I personally think it should because user is responsible for any potential resource leaks anyways if `--purge` is specified .
@Michaelvll wdyt?

**Comment by concretevitamin** [comment]
+1 to making `-p` ignore identity mismatch error. It's supposed to be an advanced/danger-zone flag to forcibly delete all things.

**Comment by concretevitamin** [comment]
Another user ran into this problem. He had no way but to go to the console to terminate a id-mismatched node. `sky down -p` didn't allow him to terminate + clean up the record. We should fix this.

**Comment by Taytay** [comment]
I am running into this right now as well. I've got two clusters in the "INIT" state (due to an issue where I was switching users), but don't know how to get rid of them. Terminating the EC2 instances is not sufficient, so clearly this is cached somewhere else. Is there a manual way to go about this in the meantime?

```
╰─ AWS_PROFILE="<my-profile>" sky down mycluster                                                               (sky) ─╯
Terminating 1 cluster: mycluster. Proceed? [Y/n]: y
'mycluster' (AWS) is owned by account '<ID>:<account>', but the activated account is '<some-other-ID>:account'.
Terminating 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
```

**Comment by concretevitamin** [comment]
@Taytay For a workaround, please run 
```
sqlite3 ~/.sky/state.db -line 'delete from clusters where name LIKE "<your cluster name>";'
```
