### ISSUE TITLE
ray is installed into the system python

### ISSUE THREAD

**Issue by eli-osherovich** [skypilot-org/skypilot#1777]
As far as I see (`arure-ray.yml.j2`) ray is installed into the system python. I see a couple of drawbacks with this approach:
1. System python packages can be changed, which may lead to instability 
2. User has no control over python version. 

It might be a better idea to create a virtual environment (with python version configurable from cli/yaml) and install ray there. 

P. S.
I Can help implementing this.

**Comment by concretevitamin** [comment]
Thanks for the report @eli-osherovich. Agreed on the 2 drawbacks. One small clarification here is we install Ray into a Conda "base" environment, not exactly the system python without any Conda env, but the drawbacks still exist:

https://github.com/skypilot-org/skypilot/blob/8df4a8bc5afd3ae9ae0ac9614fd1cb7fa7e110db/sky/templates/azure-ray.yml.j2#L99

To understand this more deeply, would you mind sharing how those two drawbacks are blocking your use case? E.g.,

- For (1): Are there concrete examples of how system python packages can be changed? Is it changed by a user job's `setup`?
- For (2): Is this an issue because your job requires using the same Ray cluster and, at the same time, a different Python version?

**Comment by eli-osherovich** [comment]
Thanks @concretevitamin .

1) My bad. Did not read the code carefully enough. Installing into a virtual environment is the right way. System python is unaffected in this case. 
2) I do want to be able to specify python/packages versions. Ideally, I would also like to see an option to not install it at all. For example, when I am using a pre-built VM image that already includes all the required packages. 

P. S.
Since we already are talking about virtual environments, don't you think that using micromamba instead of conda would be more efficient?

**Comment by concretevitamin** [comment]
We've always wanted to optimize the overheads in provisioning speed but so far haven't got to it. Exploring micromamba sounds great to me.

> I do want to be able to specify python/packages versions.
If this is the only requirement (i.e., you do not need to use the Ray cluster), one current workaround to unblock you is to create a desired virtual env (conda/mamba etc.) in your job's `setup` commands, and use it in the `run` commands. Would that work?

> Ideally, I would also like to see an option to not install it at all. For example, when I am using a pre-built VM image that already includes all the required packages.

This is interesting and we haven't thought about this!

**Comment by eli-osherovich** [comment]
> If this is the only requirement (i.e., you do not need to use the Ray cluster), one current workaround to unblock you is to create a desired virtual env (conda/mamba etc.) in your job's setup commands, and use it in the run commands. Would that work?

This is what I am doing.

P. S.
Closing this issue as all questions answered.
