### ISSUE TITLE
R2 storage copy failed with return code 255.

### ISSUE THREAD

**Issue by yudanta** [skypilot-org/skypilot#1844]
Tried the newly R2 storage support, following setup as described in the documentation got failed error ```failed with return code 255.``` 

tried to run command from the sky.exception.CommandError directly
```
mkdir -p ~/.sky/file_mounts/nli-datasets && aws --version >/dev/null 2>&1 || pip3 install awscli && aws s3 sync --no-follow-symlinks s3://<bucketname>/datasets/nli ~/.sky/file_mounts/nli-datasets --endpoint https:/<cloudflare-account-id>.r2.cloudflarestorage.com --profile=r2
```
and its working fine and the file from r2 cloned into ```~/.sky/file_mounts/nli-datasets``` directory

Versions:
skypilot, version 1.0.0-dev0
aws-cli/1.27.109 Python/3.9.15 Darwin/21.4.0 botocore/1.29.109

Cloud:
Lambdalabs

**Comment by romilbhardwaj** [comment]
Thanks for the report @yudanta. This is a bug - we'll fix it. As a temporary workaround, if you have an AWS account, enabling [AWS support](https://skypilot.readthedocs.io/en/latest/getting-started/installation.html#aws) should let you use R2 on Lambda cloud.

## Reproduction
I can confirm I can reproduce this bug with the following minimal example run in a docker container (to emulate a fresh skypilot install without aws):

```
# docker run --platform linux/amd64 -it --rm continuumio/miniconda3 /bin/bash
# Install SkyPilot
git clone https://github.com/skypilot-org/skypilot
cd skypilot 
pip install -e .
apt-get update
apt-get install rsync

# Setup lambda cloud
mkdir -p ~/.lambda_cloud
echo "api_key =<key>" > ~/.lambda_cloud/lambda_keys

# Setup R2
aws configure --profile r2
mkdir -p ~/.cloudflare
echo <account_id> > ~/.cloudflare/accountid

# Verify
sky check

# Run task
cat <<EOF >>mytask.yaml
file_mounts:
  /mymnt:
    source: r2://extbucket
    mode: COPY

run: |
  ls /mymnt
EOF
sky launch -c myclus mytask.yaml
```

This fails with:

```
I 04-10 06:27:02 backend_utils.py:1210] Syncing (to 1 node): r2://extbucket -> /mymnt
⠼ SyncingE 04-10 06:27:03 subprocess_utils.py:70]
E 04-10 06:27:03 subprocess_utils.py:70] The config profile (r2) could not be found
E 04-10 06:27:03 subprocess_utils.py:70]
Clusters
NAME           LAUNCHED        RESOURCES                          STATUS  AUTOSTOP  COMMAND
sky-efa5-root  a few secs ago  1x Lambda(gpu_1x_a10, {'A10': 1})  UP      -         sky launch -c sky-efa5-root...

sky.exceptions.CommandError: Command mkdir -p ~/.sky/file_mounts/mymnt && aws --version >/dev/null 2>&1 || pip3 install awscli && aws s3 sync --no-follow-symlinks s3://extbucket ~/.sky/file_mounts/mymnt --endpoint https://ec9997b59e5296acc10fed5cd4945e6e.r2.cloudflarestorage.com --profile=r2 failed with return code 255.
Failed to run command before rsync r2://extbucket -> /mymnt. Ensure that the network is stable, then retry.
```

## Cause
This is happening because `~/.aws/credentials` stores R2 credentials when `aws configure --profile r2` is used. However, it is not synced when AWS is not an enabled cloud. Thus the remote cluster is unable to access the R2 bucket. In the above example, I was able to fix the error by manually scping my `~/.aws/credentials` to the remote cluster.

## Fix
We need to sync `~/.aws/credentials` to remote cluster when R2 is used, even if AWS support may not be setup. Alternatively, we can see if `aws configure --profile r2` can write to another file that we can sync to remote cluster.

cc @landscapepainter

**Comment by yudanta** [comment]
thanks @romilbhardwaj  for the update, will try to manually copy the ~/.aws/credentials to the remote cluster for the quick workaround.

thanks!
