### ISSUE TITLE
[Storage] Periodic local folder/bucket syncing for better performance

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1862]
Instead of using the mounted storage, in our [Vicuna example](https://github.com/skypilot-org/skypilot/blob/master/llm/vicuna/train.yaml), we manually run a [script](https://github.com/lm-sys/FastChat/blob/main/scripts/sync_local_checkpoint.sh) to periodically sync a local disk with a folder in the mounted storage using `gsutil -m rsync` for the model checkpoints which is much faster than directly saving the checkpoint to the mounted storage. We must think of a way to integrate this logic into the SkyPilot Storage. 

```
#!/bin/bash

local_path=$1
remote_path=$2
MAX_NUM_CKPT=3

# This script is used to periodically copy local checkpoint to mounted storage
while true; do
    local_last_ckpt=$(ls ${local_path} | grep checkpoint- | grep -E '[0-9]+' | sort -t'-' -k1,1 -k2,2n | tail -1)
    remote_last_ckpt=$(ls ${remote_path} | grep checkpoint- | grep -E '[0-9]+' | sort -t'-' -k1,1 -k2,2n | tail -1)
    echo "local_last_ckpt: ${local_last_ckpt}"
    echo "remote_last_ckpt: ${remote_last_ckpt}"
    if [ "${local_last_ckpt}" != "${remote_last_ckpt}" ]; then
        mkdir -p ${remote_path}/${local_last_ckpt}
        gsutil -m rsync -r ${local_path}/${local_last_ckpt}/ ${remote_path}/${local_last_ckpt}

        # Keep only the last MAX_NUM_CKPT checkpoints
        num_local_ckpt=$(ls ${local_path} | grep checkpoint- | wc -l)
        echo "num_local_ckpt: ${num_local_ckpt}"
        if [ ${num_local_ckpt} -gt $MAX_NUM_CKPT ]; then
            for ckpt in $(ls ${local_path} | grep checkpoint- | grep -E '[0-9]+' | sort -t'-' -k1,1 -k2,2n | head -n-${MAX_NUM_CKPT}); do
                rm -rf ${local_path}/${ckpt}
            done
        fi
    fi

    sleep 600
done
```

Several things to do for the sync:
1. Upload the checksum for the checkpoint folder first, to make sure the corrupted checkpoints are not used when recovered from the preemptions
2. Need to think of the way for the API we provide. The script above assumes the checkpoints folders have specific structure, i.e.
```
CKPT_PATH/
  - checkpoint-1000/
  - checkpoint-2000/
...
```

**Comment by landscapepainter** [comment]
My understanding is that there's a necessity for a feature that periodically syncs checkpoints to cloud storage, achieved through `gsutil rsync` or `aws s3 sync`, as opposed to directly writing outputs onto a mounted cloud storage. The reason for such periodic updates, currently executed via a bash script, stems from preemptions associated with long-duration spot jobs. Therefore, this function is intrinsically tied to managed spot jobs rather than typical `sky launch`. @Michaelvll Please correct me if I'm wrong.

Currently, there are two manual tasks setup by the users. (1) We instruct the users to setup a cloud storage in `MOUNT` mode and set the mounted local directory to be the output path of the script. (2) Then, it's the users' applications script that are responsible for loading those from the directory. And I suggest we can integrating (1) as a feature while addressing all the issues above, so the users don't have to run a bash script that periodically updates the checkpoints with `gsutil rsync` or `aws s3 sync` along uploading checksum and set up a cloud storage under `file_mounts`.  

**To achieve this functionality, I propose the following:**
Ask users to pass the directory name where the checkpoints will be saved/loaded while training, and then the daemon process(or thread) we launch can periodically check if this checkpoint directory gets updated with new checkpoint and upload it to a cloud storage that users are not aware of(we do something similar with `workdir` and local `file_mounts` directory for managed spot jobs in `_maybe_translate_local_file_mounts_and_sync_up()`). And when recovering from a preemption, we can upload what's in this cloud storage to the directory user passed in while checking with checksum. Here, I assume user's application script saves checkpoint and loads the latest checkpoint when the training gets resumed.

A CLI example would look like the following:
`sky spot launch -n vicuna train-vicuna.yaml --checkpoint_dir ~/checkpoint --env WANDB_MODE=offline --env MODEL_SIZE=7`

For the running daemon process(or thread), it should be able to handle the followings:
1. maintain only x number of recent checkpoints(x is set to 3 in the current vicuna application)
2. run `gsutil rsync` or `aws s3 sync` periodically to upload checkpoints to the cloud storage
3. create checksum before uploading checkpoints and upload together

For the structure of the checkpoint directory, if we sort the checkpoints according to the time its created, either in cloud storage or in local directory, I believe it would not matter whatever structure it has. Please correct me if I'm wrong.

What do you think? @romilbhardwaj @concretevitamin @Michaelvll

**Comment by romilbhardwaj** [comment]
Thanks @landscapepainter. I think we want to retain the idea of "mounting" a folder to a bucket and keeping their contents in sync because it requires minimal assumptions about what's being stored and how it is stored.

My understanding is @Michaelvll would have used our existing `MOUNT` mode, but because gcsfuse and other FUSE utils are slow, he resorted to writing this script which syncs his checkpoint dir to his bucket periodically.

To fix, we want to improve `MOUNT` mode. We want to replace gcsfuse/goofys with something else which offers better performance and better compatibility with POSIX operations. There are two kinds of approaches we can have here:

## 1. FUSE mounting
This is the goofys/gcsfuse/s3fs approach we currently use. Syscalls get translated directly to cloud storage API calls, so we get nice consistency and durability guarantees (i.e., f.close() won't return until data is written to S3, f.open() will always fetch the latest copy on S3). However, in my experience, there are no good fuse mounting tools which offer good performance. They also suffer from lack of POSIX support, which causes issues like #1901.   

## 2. Sync contents with Bucket
This runs a daemon process which manually syncs the contents of a local dir with a cloud bucket. This sync can be triggered periodically or through inotify. @Michaelvll's script above is an example of this. This may be faster because cloud CLI tools are fairly mature and offer good performance. However, we need to be careful about consistency and durability here. For example, it's possible a task may end and autodown may kick in before the daemon has had a chance to upload the data. Similarly, if the daemon fails for any reason, the task would have no way of knowing this (since it's f.write() and f.close() operations will return successfully) and the user may silently lose data. 

-------------
In this issue, we're trying to explore the **sync contents** approach. I would recommend doing the following:

0. We benchmark `gsutil -m rsync` against  `gcsfuse` to quantify the gains we're expecting.
1. We try to find something that works off-the-shelf. We need to investigate if we can use [rclone](https://rclone.org/s3/) or seaweedfs (#1160) to periodically sync a local dir with a remote bucket.
2. If we cannot find any mature tools to do this for us OR they do not match `gsutil` in performance, we write our own daemon which syncs all "mounted" dirs with their backing object stores. This would require taking care of the durability and consistency failure modes mentioned above.
