### ISSUE TITLE
Can I specify the port to forward when running a task yaml or some other convenient way?

### ISSUE THREAD

**Issue by Taytay** [skypilot-org/skypilot#1887]
I'd like to run a jupyter notebook "task" defined in a yaml file, and when I do so, tell skypilot to forward port 8888. 
Right now, according to https://skypilot.readthedocs.io/en/latest/examples/gpu-jupyter.html, it seems like I either have to run `sky cpunode -p 8888 -c jupyter` / `sky cpunode -p 8888 -c jupyter-vm`, 
OR run `sky launch -c jupyter jupyter.yaml`

I can't define a port to be forwarded locally as part of the `sky launch` command.
So then I have to set up port forwarding after the fact myself:
`ssh -L 8888:localhost:8888 jupyter`

I thought I could do a `sky exec` and tell it to run the jupyter command AND do port forwarding, but that command doesn't seem to support it either. 

Is there something easier I am missing?

**Comment by romilbhardwaj** [comment]
Hi @Taytay - thanks for the report. Just so we can prioritize - which cloud provider are your VMs running on? 

Workaround for AWS - you can manually open the ports you need by going to the AWS cloud console and editing the rules for the security group named `sky-sg-<username>-<hash>`. You only need to do this once since the same security group is reused across runs. You can find more details in [this comment](https://github.com/skypilot-org/skypilot/issues/1255#issuecomment-1286101971). 

I believe something similar should be possible for GCP too. Also tracking in #1255.

**Comment by concretevitamin** [comment]
For simple port forwarding over SSH, we should consider supporting `-p` in `sky launch` and `sky exec`, similar to the interactive node commands.

For opening ports to the internet, it's tracked in the issues mentioned by @romilbhardwaj above.

**Comment by Taytay** [comment]
Thank you both for the quick response.
This is on AWS. 

This is a local port mapping thing  more than anything. I want to easily spin up my remote Jupyter server and be able to connect to it on "localhost:8888".

If the other commands supported the quick port mapping option, that would be ideal!
