### ISSUE TITLE
[Core] Handling cloud storages in `sky check`

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1943]
Currently `sky check` and our `CLOUD_REGISTRY` takes a compute-centric view, where clouds which have compute (i.e., VMs) enabled are listed in `sky check` and are added to enabled clouds. 

Recently, we've come across two variants needing to also handle checking if storage is available with `sky check`:
* **Cloudflare R2** (@landscapepainter) - Cloudflare is a storage-only cloud and does not offer VMs. Since it does not qualify as a regular `sky.clouds.Cloud`, we implemented one-off checks (e.g., `check_credentials` in #1865) which are invoked at various places in our code (e.g., `sky check` in #1886). This kind of special case handling, while necessary, seems like a code smell. 
* **IBM COS** (@Cohen-J-Omer ) - IBM cloud supports both VMs and storage. The VM-only credential set up requires 2 fields in `~/.ibm/credentials.py`, with which sky check returns `IBM: Enabled`. However, enabling storage support requires 3 more fields. For now we could mandate requiring all 2+3 = 5 fields before marking `IBM: Enabled`,  but this is another example of a cloud requiring different "setup" for storage. 

Do we think there's a need to maintain `enabled_storage_clouds` like we have `enabled_clouds` for VMs? `sky check` can populate `enabled_storage_clouds` which will then be useful at many places in `storage.py` where we need to validate which backing stores are available to us.

This issue is intended as an discussion. @Cohen-J-Omer @landscapepainter please feel free to chime in.

**Comment by landscapepainter** [comment]
I agree with the points @romilbhardwaj  is making about R2, IBM's separate storage credential, and being able to use `enabled_storage_clouds`. As an example, it makes more sense for functions like `task.py/get_preferred_store_type` to use `get_enabled_storage_clouds` instead of `get_enabled_clouds`. It is quite clear on the advantage of having separate method of `get_enabled_storage_clouds`, but I'm not too sure on the disadvantages. I'm thinking of more dependency adding complexity as we would have to start thinking compute instance enabled clouds and storage enabled clouds separately. What can be some other clear disadvantages? 

@Cohen-J-Omer @romilbhardwaj

**Comment by concretevitamin** [comment]
One idea here is let's wait for a user report to guide us on this. E.g., see if people actually use those stores and complain about the cases of having a cloud enabled but not its object store.

**Comment by Cohen-J-Omer** [comment]
Hey @romilbhardwaj, thanks for raising the subject.
I propose:
- Either `check_credentials()` will return a dict/list of tuples to represent compute, storage and possible future services enablement, or break the function to separate service enablement verifiers such as: `check_compute_credentials()` and `check_storage_credentials()`. 
- Unrelated to bulletin above, I suggest the UI for `sky check` will adapt a format similar to:
```
<cloud_provider>:
    Compute: enabled
    Storage: enabled
```
