### ISSUE TITLE
Specify cloud for Managed Spot

### ISSUE THREAD

**Issue by tokestermw** [skypilot-org/skypilot#1974]
Hi, is it possible to specify which cloud to use for managed spot jobs?

For example, we may want to use managed spot but only on GCP. If we wanted to de-activate AWS we can rename `~/.aws/config` and `~/.aws/credentials`, but this causes other issues (like inability to access S3).

Thanks!

**Comment by tokestermw** [comment]
Hi @Michaelvll I've tried that but it will still try to spin up AWS instances (or maybe that's the controller).

**Comment by Michaelvll** [comment]
Yes, the controller will be launched on the cloud with the cheapest price for a small CPU instance, but the actual spot clusters will be launched on the cloud you specified. In most of the time, if your job is compute heavy, the cost for the controller should be negligible. 

If you would like to move the controller to GCP as well, we currently do not expose an API to specify that. As a workaround, you may want to go to the following code and add a `cloud: gcp` in the `resources` section.
https://github.com/skypilot-org/skypilot/blob/5bb759a71aa93b9ac39e3f850bdc7fb2d4cbc0c7/sky/templates/spot-controller.yaml.j2#L5
After adding that, you may need to reinstall your SkyPilot locally, by `cd` to the root of the source code and run `pip install -e .`.

**Comment by romilbhardwaj** [comment]
It would be nice to let the user easily control which cloud the spot controller gets placed on. For a collaborator of mine, SkyPilot places the controller on Azure but they would like it to be on GCP because they have credits on GCP (but pay $$$ for Azure).

**Comment by Michaelvll** [comment]
Hi @tokestermw, we recently added a new feature to allow you to specify the resources your spot controller use. You can now specify it in `~/.sky/config.yaml` with the following specs:
```
spot:
  controller:
    resources:
      cloud: gcp
```

It should make it easier to customize the spot controller without modifying the source code directly. Note that if you have an existing controller on AWS, you may need to `sky down sky-spot-controller-<hash>` first.

I am going to close this issue since it has been resolved, but please feel free to file a new one or re-open this issue, if the solution does not satisfy your case. Thanks!
