### ISSUE TITLE
INIT/STARTING Status Stuck

### ISSUE THREAD

**Issue by xzrderek** [skypilot-org/skypilot#2126]
When trying to replicate the Vicuna example, I encountered two separate bugs that both relate to being stuck at a status INIT/STARTING.

At first, my spot jobs were stuck in the STARTING status:
<img width="703" alt="image" src="https://github.com/skypilot-org/skypilot/assets/32891260/b9ac9c8d-2dd0-4706-8574-a25fa6542a9e">

After stopping those jobs, and trying to start more, my spot controller was stuck at the INIT status:
<img width="728" alt="image" src="https://github.com/skypilot-org/skypilot/assets/32891260/080aca79-6cd2-428d-ba25-db3ab4ae3919">

I SSH'ed into the spot controller, and viewed the provision.log, and saw this error:

`Exception: {'errors': [{'code': 'QUOTA_EXCEEDED', 'message': "Quota 'NVIDIA_A100_80GB_GPUS' exceeded.  Limit: 0.0 in region us-east5.", 'errorDetails': [{'quotaInfo': {'metricName': 'compute.googleapis.com/nvidia_a100_80gb_gpus', 'limitName': 'NVIDIA-A100-80GB-GPUS-per-project-region', 'dimensions': {'region': 'us-east5'}, 'limit': 0}}]}]}`

I believe SkyPilot was endlessly trying to use every single region available, and cycling through different regions, but none had the necessary quota for the job I was trying to run, and so it was stuck in the status INIT/STARTING. Flagging because I believe a possible fix to avoid future user confusion would be to timeout after a certain amount of time or number of attempts, and some sort of feedback should be given to the user to increase their quota.

**Comment by Michaelvll** [comment]
Thanks for raising this @xzrderek!

> I believe SkyPilot was endlessly trying to use every single region available, and cycling through different regions, but none had the necessary quota for the job I was trying to run, and so it was stuck in the status INIT/STARTING. Flagging because I believe a possible fix to avoid future user confusion would be to timeout after a certain amount of time or number of attempts, and some sort of feedback should be given to the user to increase their quota.

Yes, our managed spot will keep trying all the regions infinitely. That is because our current recommended workflow would be:
1. `sky launch --use-spot task.yaml` to first debug your job in a serverful way, so that the problems like insufficient quota and errors in the code can be identified and debugged in an interactive way.
2. `sky spot launch` is designed to be a non-interactive serverless job, and we would like it to be: submit and leave it to SkyPilot.

Please let us know if that sounds good to you, or do you think there is still a gap.

> When trying to replicate the Vicuna example, I encountered two separate bugs that both relate to being stuck at a status INIT/STARTING.

It is weird that the controller is stuck in `INIT` state. Did you key interrupt the `sky spot launch` process? 

The INIT state should be fixed with a `sky start sky-spot-controller-d26214ae`.

To check the detail logs of the spot job during the `STARTING` status, you could try `sky spot logs --controller`, so you don't have to log into the controller. : )

To cancel the spot job, you should be able to `sky spot cancel -a`

**Comment by xzrderek** [comment]
That makes a lot of sense! I was unaware of the serverful way to debug my job, but that would solve the issues/confusion I was facing, thanks for clarifying.

I believe I did key interrupt the sky spot launch process, which led to the `INIT` state. I think one thing to note is that I could not `sky stop` or `sky down` the cluster since it was stuck in the `INIT` state, and to fix it, I had to go into GCP and delete it from there. Perhaps there's a gap here, since some users may not be familiar enough with GCP or other clouds to do that manually. I might've missed another way to stop or down the cluster when it's in the `INIT` state, which would also be a  good alternative.

**Comment by Michaelvll** [comment]
Sorry for the delay @xzrderek! Thanks for the feedback! That is very useful!

A workaround for that is to `sky start -y <spot-controller-name>`, and then `sky down` it, but you are right we should automate this and add more information in our doc.
