### ISSUE TITLE
[Bug] Running `sky cancel cluster_name job_id` with docker job doesn't stop job

### ISSUE THREAD

**Issue by fozziethebeat** [skypilot-org/skypilot#2340]
I've been using sky pilot to launch a lot of FastChat servers and I've noticed that the `sky cancel` command doesn't work super well with docker based jobs.

My jobs typically look something like:

```yaml
run: |
  aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_REPO_URI
  docker pull $IMAGE_ID
  docker run --rm \
    -p 80:80 \
    --env CONTROLLER_HOST=${CONTROLLER_HOST} \
    --env CONTROLLER_PORT=80 \
    --env API_PORT=80 \
    $IMAGE_ID \
    ./run_openai_api.sh
```

Its very simple:
1. Get the image
2. Run the image with some arguments

Everytime I try to cancel the docker job with a command like `sky cancel cluster-name 1`, the sky job gets canceled but the docker container is still running on the instance.  I have to ssh in manually and run `docker stop container_name`.

Is this an issue in how i start the docker container? Or is it an issue with how skypilot (and Ray) try to cancel docker jobs?

**Comment by Michaelvll** [comment]
Thanks for raising this issue @fozziethebeat! This is a known issue in SkyPilot that we are not able to kill docker job, because docker will change the parent process of its container, causing SkyPilot to fail to find the process to be killed when the `sky cancel` is called.

We have to look into this issue. 

One effort we are trying to make is PR #1910, where you can specify your docker image in `image_id` of the resources field in the yaml file. With that, all your setup and run sections will be run in the container, and the `sky cancel` will be killing a process in that container. Also, your `ssh` will go into the container as well.

Please let us know if that workaround can work. : )

**Comment by cblmemo** [comment]
Hi @frozziethebeat thanks for the feedback! We are merging #1910 and designing the login feature you mentioned here. Currently, we have two solutions. The first one is to specify your docker username, password and project URI in `~/.sky/config.yaml`:

```yaml
docker:
  username: <your username>
  password: <your password, plain text or a filename that stores your password>
  project_uri: <your project uri>
```

This only requires one setup and all your following sky commands will use the configuration here. The second design is to specify these through `task.yaml`'s `envs` section:

```yaml
envs:
  DOCKER_USERNAME: xx
  DOCKER_REPO_URI: xxx
  DOCKER_PASSWORD: xxx
```

This is useful when you have different project for different tasks, and you could generate them with some CLI commands, such as

```bash
sky launch --env DOCKER_PASSWORD =`aws ecr get-login-password --region us-east-1`
```

Which one would you prefer?

**Comment by fozziethebeat** [comment]
Oh that's awesome!

For my use case the second works best since I'm pulling docker images from both GCP's image repo and AWS's image repo.  I've been semi simulating the second solution with different .env files so this should fit pretty naturally.

**Comment by cblmemo** [comment]
Hey @fozziethebeat we just merged the feature - feel free to try it out!

**Comment by fozziethebeat** [comment]
Rad! I shall soon!
