### ISSUE TITLE
[k8s] `sky local up` shows `Docker is not running` while docker is running

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#2592]
The CLI command `sky local up` shows following error:
```bash
$ sky local up                           
⠋ Creating local cluster...
Failed to create local cluster. Docker is not running. Please start Docker and try again.
```
After checking the scripts and manually run `docker info`, it seems like some permission issues:
```bash
$docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```

Shall we add `sudo` before the `docker` commands in the `sky/utils/kubernetes/create_cluster.sh`?

**Comment by romilbhardwaj** [comment]
Ah thanks for catching this @cblmemo. I think most environments create a docker group with permissions to the docker socket and add users who should have access to docker to this group (see [post-install instructions](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)). Requiring sudo in create_cluster.sh would require a more permissive environment (i.e., users have sudo access instead of just access to the docker socket), which some users may not have.

That said, I do think we should update the `sky local up` error msg to check if it's a permission problem, and show the correct error message instead of `Docker is not running`.
