### ISSUE TITLE
[k8s] Avoid placing non-GPU tasks on GPU nodes

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2623]
In a heterogeneous cluster with both CPU and GPU nodes, we should avoid placing CPU-only SkyPilot clusters on GPU nodes. Can be easily achieved with pod/node affinity labels.

**Comment by xzrderek** [comment]
This issue is resolved by Kubernetes by using the concept of taints/tolerations, and both GKE and EKS handle it. Specifically, the node taint "Key: nvidia.com/gpu, Effect: NoSchedule" is applied to GPU nodes. This causes only pods requesting GPUs to be scheduled on GPU nodes. In other words, CPU-only jobs will not be placed on GPU nodes. You may find relevant GKE documentation describing this in detail [here](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus) and EKS documentation [here](https://docs.aws.amazon.com/eks/latest/userguide/node-taints-managed-node-groups.html). 

This has also been verified by testing on both GKE and EKS. Specifically, you may witness the following behavior by running the following:
1. Create a heterogenous cluster using either GKE or EKS following [this](https://github.com/skypilot-org/skypilot/tree/master/tests/kubernetes)
2. Run `sky launch --cpus 2` to launch a CPU-only job
3. Run `kubectl describe pod`, and see that the node used will always be the CPU-only node
4. You can verify the taint/toleration being used by checking for the below output after running the command in 3:

> Tolerations:                
node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
nvidia.com/gpu:NoSchedule op=Exists

**Comment by romilbhardwaj** [comment]
Thanks @xzrderek! Closing this issue for now.
