### ISSUE TITLE
[Feature Request] Print Public IP in the final output

### ISSUE THREAD

**Issue by sunny0826** [skypilot-org/skypilot#2629]
I would like to be able to print the **Public IP** and **port** in the final output of `launch` when the `ports` field is set. This way I don't have to use the `sky status --ip tabby` command to get the Public IP every time.

Just one line of output can greatly enhance the user experience. 😊 I can come and implement this little feature if I can.

**Comment by concretevitamin** [comment]
My hunch is that for serving workloads, this makes complete sense. But for batch jobs we may not want to emphasize low level details like `ip` in the default `sky launch` output. Two alternatives:
- Are you scripting? If so, does enhancing `sky status --ip` to print the port work?
- For `sky launch`, ok to print the ip and port if `resources.ports` is detected (otherwise, don't print)

**Comment by sunny0826** [comment]
Yep, so I added "when the `ports` field is set" to the issue description. Even further, flags like `--browser` can be added to `sky launch` to automatically evoke the browser.

**Comment by concretevitamin** [comment]
> Yep, so I added "when the `ports` field is set" to the issue description.

Oops, missed that part. Sounds good! One detail to note: some clusters may be launched in private VPC and have no public IPs assigned.
