### ISSUE TITLE
[Documentation] Clarify different use cases

### ISSUE THREAD

**Issue by cyril94440** [skypilot-org/skypilot#2830]
Hi there,

Thank you for the exceptional work you've done; it's truly revolutionary!

I have several queries about various scenarios that I'm finding difficult to envision, and I would greatly appreciate some clarification in the documentation:

1 - Spot Instances
It seems that SkyPilot's spot instances are primarily designed for finite tasks like training. However, I believe using them for ongoing tasks such as serving inference, despite potential interruptions, would be fantastic. I've experimented with running an inference server via Docker on a spot instance, encountering only the issue of a closed port. While I could open it manually, it would close again if the instance were interrupted. Is SkyPilot suitable for such usage? Additionally, in the event of an interruption, can SkyPilot redeploy an instance on a different cloud, or is a cluster once deployed bound to a specific cloud?

2 - DevOps
I'm struggling to find resources that detail how to construct a comprehensive DevOps pipeline using SkyPilot, possibly integrating with tools like Terraform. In this setup, one could configure deployments through SkyPilot and manage all surrounding resources, transforming SkyPilot from merely a "toolkit/CLI" into a sophisticated provisioning service. Can SkyPilot be incorporated into a full production pipeline, or is it primarily intended for training and R&D?

3 - GPU Sharing
I'm curious about whether SkyPilot can be utilized in scenarios where multiple containers run on a single GPU. While it's primarily designed for Gen AI, which typically fully utilizes the GPU, it would be beneficial in other scenarios to allocate a specific amount of VRAM and automatically assign Docker containers accordingly (a feature even Kubernetes lacks). Alternatively, is it feasible to launch multiple Docker containers on a single instance with spot auto-recovery?

Thank you for your time.

**Comment by Michaelvll** [comment]
Thanks for the questions @cyril94440! We should definitely improve our documents (a bunch of recent updates haven't been listed on the doc yet). : )

> 1. Spot instances

Regarding the ports, could you say more how you start the docker container? Our task yaml supports openning ports of the VM launched by specifying the following field in `resources`, so that whenever the cluster is preempted and restarted the ports should still be open to public.
```yaml
resources:
  ports: 8080

run: |
  docker run --net host my-image:latest
```

Additionally, we have released our SkyServe support, which will further guarantee that the endpoint you use will not change after preemption and recoveries:
```yaml
resources:
  port: 8080
  use_spot: true

service:
  readiness_probe: /v1/models
  replicas: 2
 
run: |
  docker run --net host my-image:latest
```
`sky serve up service.yaml` will give you a single endpoint and get your traffic automatically load balanced across multiple replicas of your model.

> Additionally, in the event of an interruption, can SkyPilot redeploy an instance on a different cloud, or is a cluster once deployed bound to a specific cloud?

This depends on whether you specify the `cloud` field under `resources`. If not specified, SkyPilot will go through all the enabled clouds to find available spot instances for you. 


> 2. DevOps

This is a great request! Making SkyPilot a service is on our radar -- we are currently trying to figure out the best way to make this work. Currently, we are focusing on LLM and AI use cases, and trying to make our user successful for their workloads. 
For the integration with a production pipeline,  we are excited to hear more from you about the detailed use case and see how can we support it. We will reach out to you through our slack. ; )

> 3 - GPU Sharing

If you would like to launch multiple dockers on a single VM, it should be possible as SkyPilot can take any bash script as the `run` field. If you are interested, here is an example of how we launched multiple dockers for our previous tutorial session for SkyPilot: https://github.com/Michaelvll/skycamp23-infra/blob/1f86357e38b4ef0bffd80afee1233da4af4e8357/create_nodes.py#L68-L79

**Comment by concretevitamin** [comment]
> One last question, from my tests it looked like spot interruption notices were not handled resulting in interruptions which is an issue for live workloads. Do I have misconfigured something or is it not ready yet?

Hello @cyril94440 -- is it possible that you were using `sky launch --use-spot`? If so, it is “unmanaged” and will print
```
I 12-04 08:55:41 execution.py:287] Launching an unmanaged spot task, which does not automatically recover from preemptions.
I 12-04 08:55:41 execution.py:287] To get automatic recovery, use managed spot instead: sky spot launch or sky.spot_launch().
```

To have auto-recovery, there are two options:
- `sky spot launch <yaml>`, designed for batch jobs on spot instances, although people have also used it for adhoc serving
- `sky serve up <service yaml>` (be sure to set `use_spot: True`), [designed](https://github.com/skypilot-org/skypilot/blob/a4dcc3c534473a8815ef64fe42b3ed6ac71f6ce3/docs/source/examples/sky-serve.rst) for real serving workloads
