### ISSUE TITLE
Smoke Test Failure - using_file_mounts_with_env_vars

### ISSUE THREAD

**Issue by dmatch01** [skypilot-org/skypilot#3033]
Getting the following failure when running the smoke test. 
```
$ pytest tests/test_smoke.py --terminate-on-failure
. . .
[using_file_mounts_with_env_vars] Failed.
[using_file_mounts_with_env_vars] Reason: sky launch -y -c t-using-file-mounts-w-42-be --cpus 2+ --cloud gcp examples/using_file_mounts_with_env_vars.yaml
[using_file_mounts_with_env_vars] Log: less /tmp/using_file_mounts_with_env_vars-xo04zbnn.log
. . .
$ cat /tmp/using_file_mounts_with_env_vars-xo04zbnn.log
. . .
sky.exceptions.StorageBucketGetError: Failed to access existing bucket 'skypilot-temp-gcs-test'. This is likely because it is a private bucket you do not have access to.
```
Suggestions on how to resolve?  Thanks in advance!

**Comment by romilbhardwaj** [comment]
Hmm, can you try changing L6 in `examples/using_file_mounts_with_env_vars.yaml` 
https://github.com/skypilot-org/skypilot/blob/83a9dc395b430f9c4c6076f6196b4cfe303bdff5/examples/using_file_mounts_with_env_vars.yaml#L6

to use some other bucket name, example
```
MY_BUCKET: myuniqueskybucket321
```

We may need to update our smoke tests to dynamically generate the bucket name instead of using a hardcoded one.

**Comment by dmatch01** [comment]
Thanks @romilbhardwaj for the comment. I was thinking that this might be a hardcoded issue in the smoke test but wanted to confirm.  I'll submit a PR fix for this as well.
