### ISSUE TITLE
[Storage] Allow users to specify regions of the created buckets.

### ISSUE THREAD

**Issue by landscapepainter** [skypilot-org/skypilot#3127]
related: #3114 
User wants to create a bucket in specific region. If it's necessary to specify multiple regions, we may need to consider adding a new field under `file_mounts`. If a single region is enough, we should investigate how this can be done by setting it from `~/.sky/config.yaml`

**Comment by concretevitamin** [comment]
This is a long standing issue.
- Bucket creation is eager
- We currently don't do a good job of creating a bucket in the chosen compute region/cloud

In #3114, users already express the intent of "where my compute can be", so I'm not sure if we should additionally specify "where my storage can be".

**Comment by manzke** [comment]
Let's say I would be fine if the storage is where my compute is.
Not necessarily need to specify run in A but have it in B.
That would be a nice feature, which sometimes could be interesting. (But at the end I can control it through where compute is)

Interesting scenario to think through:
- I start in eu central
- controller and so one are spin up
- bucket too

What happens if a spot instance in eu west starts? (I wouldn't need to have the bucket moved, but thought I bring it up)
