### ISSUE TITLE
[Spot] Why is `.git` excluded for bucket sync?

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#3297]
User using managed spot job asked:

> I want to sync up my .git folder too to workdir, how I can do so? is there a way to include it? would a symlink work (then renaming it in setup section) or is there a cleaner way to do it

Currently in `storage.py` (bucket mounts) we ignore `.git`. (cc @Michaelvll @romilbhardwaj do you remember why we did it this way?) 

Here's a workaround:
```
# Usage: 
#  sky spot launch sky.yaml

workdir: .

file_mounts:
  ~/sky_workdir/.git: .git

run: |
  set -ex
  ls -lthra .git
  git log
  git show
```

**Comment by Michaelvll** [comment]
> User using managed spot job asked:
> 
> > I want to sync up my .git folder too to workdir, how I can do so? is there a way to include it? would a symlink work (then renaming it in setup section) or is there a cleaner way to do it
> 
> Currently in `storage.py` (bucket mounts) we ignore `.git`. (cc @Michaelvll @romilbhardwaj do you remember why we did it this way?)
> 
> Here's a workaround:
> 
> ```
> # Usage: 
> #  sky spot launch sky.yaml
> 
> workdir: .
> 
> file_mounts:
>   ~/sky_workdir/.git: .git
> 
> run: |
>   set -ex
>   ls -lthra .git
>   git log
>   git show
> ```

This was likely because `.git` folder can easily have many small files, and can take a long time uploading the cloud bucket (object store is not very friendly with small files). Since most cloud bucket API does not support the rsync alike way to exclude folders in `.gitignore` style argument, we removed it from our upload list.

This seems related to #3188, with which we can tar the folders to be uploaded to reduce the overhead for uploading small files.
