### ISSUE TITLE
[UX][feature request] Make cost a first-class citizen

### ISSUE THREAD

**Issue by gaocegege** [skypilot-org/skypilot#4503]
A notable benefit of multi-cloud, particularly in inference scenarios, is cost savings. However, tracking costs in a multi-cloud inference environment can be challenging. While this could be a valuable feature for Skypilot, I haven't seen much emphasis on it yet.

Implementing cost observability would be advantageous, giving teams(data science, admin, and the boss) visibility into both current and historical cloud expenditures and resource allocation.

I think it would really help to start with `sky serve`, especially since it's so important for inference. Knowing the costs is key, **especially when you have replicas in AWS and others in GCP**. It doesn't have to be in the terminal UI, but it could be nice to see the total cost and cost per hour near the region info. Just a thought.

![image](https://github.com/user-attachments/assets/449931f9-065a-4224-ac42-66605a683660)

Cost metrics could be offered through a separate command, like sky cost, or simply displayed in the dashboard.

Just raise the issue to kick off the discussion. It’s not a precise idea yet, but I think it could lead to some interesting conversations.

**Comment by gaocegege** [comment]
The basic idea is to make cost a first-class citizen, similar to jobs and service.

**Comment by romilbhardwaj** [comment]
Thanks for the feedback @gaocegege. We have an experimental `sky cost-report` feature (the [documentation](https://docs.skypilot.co/en/latest/reference/cli.html#sky-cost-report) is limited since it's experimental). 

![image](https://github.com/user-attachments/assets/b3260607-d2d1-46b1-a446-945ce47d8a9d)

We welcome any proposals and contributions to make it more robust and extend it to sky serve and managed jobs.

**Comment by gaocegege** [comment]
Thanks for the guide! It meets my needs, so I'm going to close this.
