### ISSUE TITLE
User Ray and Sky Ray version conflicts

### ISSUE THREAD

**Issue by gmittal** [skypilot-org/skypilot#671]
Justin’s requirements.txt will install ray. If the version of ray does not equal our ray version, it will cause some problems. Maybe we should encourage the user to use conda environment?

**Comment by Michaelvll** [comment]
Another user requested to launch their own ray cluster on the machines launched by skypilot:
> The rough setup is as follows:
> * I need to launch our own copy of the ray clusters inside singularity inside bazel, with all our dependencies available and loaded.
> * For each job submitted by sky, I launch a separate ray cluster, since each job may have their own bazel-built dependencies that need to be made available to the ray workers.
> * Ideally, I’d like to stop any existing ray clusters (launched by us, not sky) before a job starts, and after a job is finished.
> * Because singularity has less isolation than docker, I can’t just call ray stop since it also stops the ray cluster launched by sky running on the host VMs directly.

As suggested by the user, we can launch our ray cluster on non-default ports, so that the user trying to launch a ray cluster will not suffer from the problem where the ports being taken by our ray cluster. It may need some investigations to make sure that multiple ray cluster can work well with each other (we also need the instruction in FAQ).
https://docs.ray.io/en/latest/ray-core/configure.html#ports-configurations

**Comment by Michaelvll** [comment]
Another potential user is blocked by this as their program depends on a specific version of ray.
